#!/bin/bash
sudo apt-get update

for i in nodejs lua5.3 luajit python3-pip python3-setuptools node-typescript npm
do if which $i
    then echo "# $i installed"
    else sudo apt-get install -y $i
    fi
done

sudo ln -s /usr/bin/nodejs /usr/bin/node

if which pycco 
    then echo "pycco installed"
    else
        git clone git://github.com/pycco-docs/pycco.git ./temp
        sudo python3 ./temp/setup.py install
        rm -rf /temp
fi

echo "Transpiling Typescript code ..."
cd src
tsc sortlastcol.ts
tsc argmin.ts
tsc Pipe3.ts
echo "Transpiling completed"

chmod +x run2
../etc/ide
